language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  app: challenge-yourself
  api_key:
    secure: H8J743YGCGG7KzICf+kadzqAxblq5rnOMoXMP+CCr67ofVqhls+D0EL87aUlAGG7GO538/uWpp41Zy/06ZFYEBU++56nyF7YoXICDRQE2Z/oU6vOoMVOu8Ch7SWdjI2M5MhN6VNlhnd89YjoDWqdu6DLrlBKCHyB/dmgXRrNGnb6RdbDf3ZVOnbQFUuUbcXPUlmyv7A0ysZvLgojL8f3MEDzVU9TYbBGKtrJJluv2K6m/NDCHpe2C4dZSLakiLV97ks3nbl5SaDY66lFltg4Gz3qAi3hA6rUUoc8IhGnjTjubGoNc6BI2ctMQWlECb0nOCyPG1nBQmcIauta+KkxUo9pANWK2S1J+bl4oky32XHc1kySeRQ15kM3D8zDVzLnXxLTlwFG2F78GSKGINsR5MaCVxQNnxPODujYmsHp3IUww2E1OGS31C3oFmIA+MGWSm9+MWG7kmgH5oDAzKbplOTJGbuHLGrwgCUt+JURo0Xz3rW+aE6sCZ65KVRqK6+n+nU+/ALp7tyQuH+jJ9bS9Z4k/w8QkyCVAaX44roWTFpSuML3emfqFmeShT/7wvCDz032aL4QcZGUsu9yxYcWdlf3RC68QjpDatvipIS97h/ZjJBTpTefPVfE6+fe85fzdrM5FNS8Ic0CBsp+4q3Mv1mI4Ge0mLZw68nAEft7Nto=
